/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.font.TextAttribute;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mal.User;

/**
 *
 * @author HP
 */

public class MyProfile extends javax.swing.JFrame {

    /**
     * Creates new form MyProfile
     */
    User currentUser;
    
    public MyProfile(User curentUser) {
        this.currentUser = curentUser;
        initComponents();
        
        populate();
        
    }
    
    
    public void populate(){
        
        updateInfo();
        updateActivityBoard();
        updatePokeList();
    }
    
    public void updateInfo(){
        nameLabel.setText(currentUser.name);
        followingsLabel.setText("Following(" + currentUser.followingList.following.size() + ")");
        followersLabel.setText("Followers(" + currentUser.followingList.follower.size() + ")");
        friendsLabel.setText("Friends(" + currentUser.friendList.friendList.size() + ")");
        relationStatusLabel.setText((!(currentUser.maritalStatus == null)) ? currentUser.maritalStatus : "Not Available");
        aboutStatus.setText((!(currentUser.maritalStatus == null)) ? currentUser.status : "Not Available");
    }
    
    public void updateActivityBoard(){
        String[] strings = new String[currentUser.friendList.friendList.size()];
            
        int index = 0;
        for(String username : currentUser.friendList.friendList.keySet())
            strings[index++] = currentUser.friendList.friendList.get(username).username;
        
        activityList.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        activityList.setModel(new javax.swing.AbstractListModel<String>() {
            
            
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(activityList);
    }
    
    public void updatePokeList(){
        String[] strings = new String[currentUser.poke.pokeList.size()];
        int index = 0;
        System.out.println("Poke list size: " + currentUser.poke.pokeList.size());
        
        for(String username : currentUser.poke.pokeList.keySet())
            strings[index++] = currentUser.poke.pokeList.get(username).username;
        
         pokedList.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        pokedList.setModel(new javax.swing.AbstractListModel<String>() {
            
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(pokedList);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        profile = new javax.swing.JLabel();
        inbox = new javax.swing.JLabel();
        logout1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pokedList = new javax.swing.JList<>();
        pokeBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        followingLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel13 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        followingsLabel = new javax.swing.JLabel();
        followersLabel = new javax.swing.JLabel();
        followingLabel3 = new javax.swing.JLabel();
        friendsLabel = new javax.swing.JLabel();
        followingLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        aboutStatus = new javax.swing.JTextArea();
        relationStatusLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        activityList = new javax.swing.JList<>();
        sendmessage = new javax.swing.JButton();
        pokeButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel1.setText("MAL Network");

        search.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        search.setText("Search by username");
        search.setToolTipText("Search...");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        profile.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        profile.setText("NewsFeed");
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileMouseExited(evt);
            }
        });

        inbox.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        inbox.setText("Inbox");
        inbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inboxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inboxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inboxMouseExited(evt);
            }
        });

        logout1.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        logout1.setText("Logout");
        logout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout1MouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(236, 236, 236));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(27, 540, 0, 0);

        nameLabel.setFont(new java.awt.Font("Product Sans", 1, 36)); // NOI18N
        nameLabel.setText("Maryam Inam");
        nameLabel.setToolTipText("");
        nameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nameLabelMouseExited(evt);
            }
        });
        jPanel1.add(nameLabel);
        nameLabel.setBounds(250, 170, 300, 50);

        pokedList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 4, true));
        pokedList.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        pokedList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ali", "Ammar", "Hammad", "Maryam", "Labwa", "ATC" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        pokedList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                pokedListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(pokedList);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(750, 490, 190, 200);

        pokeBack.setBackground(new java.awt.Color(255, 0, 51));
        pokeBack.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        pokeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/poke.png"))); // NOI18N
        pokeBack.setText("Poke Back");
        pokeBack.setEnabled(false);
        pokeBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokeBackMouseClicked(evt);
            }
        });
        pokeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokeBackActionPerformed(evt);
            }
        });
        jPanel1.add(pokeBack);
        pokeBack.setBounds(800, 700, 140, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(658, 296, 0, 2);

        followingLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        followingLabel.setText("About:");
        jPanel1.add(followingLabel);
        followingLabel.setBounds(40, 570, 50, 18);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(387, 886, 2, 0);
        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(415, 737, 2, 2);

        jLabel13.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jLabel13.setText("People who poked you");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(750, 460, 178, 23);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Change password");
        jButton11.setBorder(null);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(800, 250, 140, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 110, 190, 220);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coverj.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 960, 240);

        jLabel2.setFont(new java.awt.Font("Product Sans", 1, 14)); // NOI18N
        jLabel2.setText("Profile Information");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 380, 130, 18);

        followingsLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        followingsLabel.setForeground(new java.awt.Color(255, 51, 51));
        followingsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-female-profile-16.png"))); // NOI18N
        followingsLabel.setText("Following (7) ");
        followingsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        followingsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                followingsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                followingsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                followingsLabelMouseExited(evt);
            }
        });
        jPanel1.add(followingsLabel);
        followingsLabel.setBounds(40, 430, 110, 18);

        followersLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        followersLabel.setForeground(new java.awt.Color(255, 51, 51));
        followersLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-female-profile-16.png"))); // NOI18N
        followersLabel.setText("Followers (7) ");
        followersLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        followersLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                followersLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                followersLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                followersLabelMouseExited(evt);
            }
        });
        jPanel1.add(followersLabel);
        followersLabel.setBounds(40, 460, 110, 18);

        followingLabel3.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        followingLabel3.setForeground(new java.awt.Color(255, 51, 51));
        followingLabel3.setText("Change about status");
        followingLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        followingLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                followingLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                followingLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                followingLabel3MouseExited(evt);
            }
        });
        jPanel1.add(followingLabel3);
        followingLabel3.setBounds(40, 700, 140, 18);

        friendsLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        friendsLabel.setForeground(new java.awt.Color(255, 51, 51));
        friendsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-female-profile-16.png"))); // NOI18N
        friendsLabel.setText("Friends (7) ");
        friendsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        friendsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friendsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                friendsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                friendsLabelMouseExited(evt);
            }
        });
        jPanel1.add(friendsLabel);
        friendsLabel.setBounds(40, 490, 110, 18);

        followingLabel5.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        followingLabel5.setText("Relationship Status:");
        jPanel1.add(followingLabel5);
        followingLabel5.setBounds(40, 520, 140, 18);

        aboutStatus.setEditable(false);
        aboutStatus.setColumns(20);
        aboutStatus.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        aboutStatus.setLineWrap(true);
        aboutStatus.setRows(5);
        aboutStatus.setText("Status will be displayed here whatever you choose");
        jScrollPane3.setViewportView(aboutStatus);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(40, 590, 246, 100);

        relationStatusLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        relationStatusLabel.setForeground(new java.awt.Color(255, 51, 51));
        relationStatusLabel.setText("Single");
        relationStatusLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        relationStatusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relationStatusLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                relationStatusLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                relationStatusLabelMouseExited(evt);
            }
        });
        jPanel1.add(relationStatusLabel);
        relationStatusLabel.setBounds(40, 540, 200, 18);

        jPanel3.setBackground(new java.awt.Color(236, 236, 236));
        jPanel3.setLayout(null);

        activityList.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        activityList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        activityList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                activityListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(activityList);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(20, 60, 390, 350);

        sendmessage.setBackground(new java.awt.Color(255, 255, 255));
        sendmessage.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        sendmessage.setText("Send Message");
        sendmessage.setEnabled(false);
        sendmessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendmessageMouseClicked(evt);
            }
        });
        sendmessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmessageActionPerformed(evt);
            }
        });
        jPanel3.add(sendmessage);
        sendmessage.setBounds(140, 420, 130, 40);

        pokeButton.setBackground(new java.awt.Color(255, 204, 204));
        pokeButton.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        pokeButton.setText("Poke");
        pokeButton.setEnabled(false);
        pokeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokeButtonMouseClicked(evt);
            }
        });
        pokeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokeButtonActionPerformed(evt);
            }
        });
        jPanel3.add(pokeButton);
        pokeButton.setBounds(280, 420, 130, 40);

        jLabel4.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Activity Board (Friend List)");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 30, 310, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhh.jpg"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(4, 4, 420, 500);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(300, 240, 430, 500);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(inbox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profile)
                        .addComponent(logout1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseClicked
        // TODO add your handling code here:
        Login r = new Login();
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logout1MouseClicked

    private void inboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inboxMouseClicked
        // TODO add your handling code here:
        Inbox r = new Inbox(MyProfile.this ,currentUser.username);
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_inboxMouseClicked

    private void profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseEntered
        // TODO add your handling code here:
         Font font = profile.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        profile.setFont(font.deriveFont(attributes));
        profile.setForeground(Color.pink);
        
    }//GEN-LAST:event_profileMouseEntered

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
        System.out.println("clicked");
        Newsfeed r = new Newsfeed(currentUser);
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        // TODO add your handling code here:
        search.setText("");
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void pokeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokeBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pokeBackActionPerformed

    private void pokeBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokeBackMouseClicked
        // TODO add your handling code here:kkkkkkkkkkkkk
        currentUser.poke(currentUser.poke.pokeList.get(pokedList.getSelectedValue()));
        JOptionPane.showMessageDialog(this, "Poke sent to: " + currentUser.poke.pokeList.get(pokedList.getSelectedValue()));
    }//GEN-LAST:event_pokeBackMouseClicked

    private void pokeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokeButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pokeButtonActionPerformed

    private void sendmessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendmessageActionPerformed

    private void followingsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_followingsLabelMouseClicked
        // TODO add your handling code here:
        
        FollowingerList r = new FollowingerList(currentUser ,1);
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_followingsLabelMouseClicked

    private void activityListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_activityListValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            pokeButton.setEnabled(true);
            sendmessage.setEnabled(true);
        }
    }//GEN-LAST:event_activityListValueChanged

    private void pokeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokeButtonMouseClicked
        // TODO add your handling code here:
        
        currentUser.poke(currentUser.friendList.friendList.get(activityList.getSelectedValue()));
        
        JOptionPane.showMessageDialog(this, "Poke sent to: " + currentUser.friendList.friendList.get(activityList.getSelectedValue()));
    }//GEN-LAST:event_pokeButtonMouseClicked

    private void pokedListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_pokedListValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            pokeBack.setEnabled(true);
        }
    }//GEN-LAST:event_pokedListValueChanged

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        ChangePassword r = new ChangePassword(currentUser);
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton11MouseClicked

    private void sendmessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendmessageMouseClicked
        // TODO add your handling code here:
        
        SendMessage r = new SendMessage(currentUser ,currentUser.friendList.friendList.get(activityList.getSelectedValue()));
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_sendmessageMouseClicked

    private void relationStatusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relationStatusLabelMouseClicked
        // TODO add your handling code here:
        ChangeRelationship r = new ChangeRelationship(currentUser);
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_relationStatusLabelMouseClicked

    private void followingLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_followingLabel3MouseClicked
        // TODO add your handling code here:
        ChangeAboutStatus r = new ChangeAboutStatus(currentUser);
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_followingLabel3MouseClicked

    private void followersLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_followersLabelMouseClicked
        // TODO add your handling code here:
         FollowingerList r = new FollowingerList(currentUser ,2);
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_followersLabelMouseClicked

    private void friendsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friendsLabelMouseClicked
        // TODO add your handling code here:
        
        ViewFriends r = new ViewFriends(currentUser);
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_friendsLabelMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        NewFriend r = new NewFriend(currentUser, search.getText());
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        }
        
    }//GEN-LAST:event_searchKeyPressed

    private void followingsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_followingsLabelMouseEntered
        // TODO add your handling code here:
          Font font = followingsLabel.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        followingsLabel.setFont(font.deriveFont(attributes));
        followingsLabel.setForeground(Color.black);
    }//GEN-LAST:event_followingsLabelMouseEntered

    private void followingsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_followingsLabelMouseExited
        // TODO add your handling code here:
         Font font = followingsLabel.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        followingsLabel.setFont(font.deriveFont(attributes));
        followingsLabel.setForeground(Color.pink);
        
    }//GEN-LAST:event_followingsLabelMouseExited

    private void followersLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_followersLabelMouseEntered
        // TODO add your handling code here:
        
          Font font = followersLabel.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        followersLabel.setFont(font.deriveFont(attributes));
        followersLabel.setForeground(Color.black);
    }//GEN-LAST:event_followersLabelMouseEntered

    private void followersLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_followersLabelMouseExited
        // TODO add your handling code here:
        
        Font font = followersLabel.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        followersLabel.setFont(font.deriveFont(attributes));
        followersLabel.setForeground(Color.pink);
    }//GEN-LAST:event_followersLabelMouseExited

    private void friendsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friendsLabelMouseEntered
        // TODO add your handling code here:
        
          Font font = friendsLabel.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        friendsLabel.setFont(font.deriveFont(attributes));
        friendsLabel.setForeground(Color.black);
    }//GEN-LAST:event_friendsLabelMouseEntered

    private void friendsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friendsLabelMouseExited
        // TODO add your handling code here:
        
         Font font = friendsLabel.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        friendsLabel.setFont(font.deriveFont(attributes));
        friendsLabel.setForeground(Color.pink);
    }//GEN-LAST:event_friendsLabelMouseExited

    private void relationStatusLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relationStatusLabelMouseEntered
        // TODO add your handling code here:
        Font font = relationStatusLabel.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        relationStatusLabel.setFont(font.deriveFont(attributes));
        relationStatusLabel.setForeground(Color.black);
    }//GEN-LAST:event_relationStatusLabelMouseEntered

    private void relationStatusLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relationStatusLabelMouseExited
        // TODO add your handling code here:
        Font font = relationStatusLabel.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        relationStatusLabel.setFont(font.deriveFont(attributes));
        relationStatusLabel.setForeground(Color.pink);
        
    }//GEN-LAST:event_relationStatusLabelMouseExited

    private void followingLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_followingLabel3MouseEntered
        // TODO add your handling code here:
        
        Font font = followingLabel3.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        followingLabel3.setFont(font.deriveFont(attributes));
        followingLabel3.setForeground(Color.black);
    }//GEN-LAST:event_followingLabel3MouseEntered

    private void followingLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_followingLabel3MouseExited
        // TODO add your handling code here:
        Font font = followingLabel3.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        followingLabel3.setFont(font.deriveFont(attributes));
        followingLabel3.setForeground(Color.pink);
        
    }//GEN-LAST:event_followingLabel3MouseExited

    private void inboxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inboxMouseEntered
        // TODO add your handling code here:
         Font font = inbox.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        inbox.setFont(font.deriveFont(attributes));
        inbox.setForeground(Color.pink);
    }//GEN-LAST:event_inboxMouseEntered

    private void inboxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inboxMouseExited
        // TODO add your handling code here:
        Font font = inbox.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        inbox.setFont(font.deriveFont(attributes));
        inbox.setForeground(Color.black);
    }//GEN-LAST:event_inboxMouseExited

    private void profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseExited
        // TODO add your handling code here:
        
         Font font = profile.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        profile.setFont(font.deriveFont(attributes));
        profile.setForeground(Color.black);
    }//GEN-LAST:event_profileMouseExited

    private void logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseEntered
        // TODO add your handling code here:
         Font font = logout1.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        logout1.setFont(font.deriveFont(attributes));
        logout1.setForeground(Color.pink);
    }//GEN-LAST:event_logout1MouseEntered

    private void logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseExited
        // TODO add your handling code here:
        Font font = logout1.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        logout1.setFont(font.deriveFont(attributes));
        logout1.setForeground(Color.black);
    }//GEN-LAST:event_logout1MouseExited

    private void nameLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameLabelMouseEntered
        // TODO add your handling code here:
        nameLabel.setForeground(Color.pink);
    }//GEN-LAST:event_nameLabelMouseEntered

    private void nameLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameLabelMouseExited
        // TODO add your handling code here:
        nameLabel.setForeground(Color.black);
    }//GEN-LAST:event_nameLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyProfile().setVisible(true);
            }
        });
*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aboutStatus;
    private javax.swing.JList<String> activityList;
    private javax.swing.JLabel followersLabel;
    private javax.swing.JLabel followingLabel;
    private javax.swing.JLabel followingLabel3;
    private javax.swing.JLabel followingLabel5;
    private javax.swing.JLabel followingsLabel;
    private javax.swing.JLabel friendsLabel;
    private javax.swing.JLabel inbox;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logout1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton pokeBack;
    private javax.swing.JButton pokeButton;
    private javax.swing.JList<String> pokedList;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel relationStatusLabel;
    private javax.swing.JTextField search;
    private javax.swing.JButton sendmessage;
    // End of variables declaration//GEN-END:variables
}
